package com.lyh.cn.passwordbook.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lyh.cn.passwordbook.model.PwdInfo;

import com.lyh.cn.passwordbook.greendao.PwdInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pwdInfoDaoConfig;

    private final PwdInfoDao pwdInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pwdInfoDaoConfig = daoConfigMap.get(PwdInfoDao.class).clone();
        pwdInfoDaoConfig.initIdentityScope(type);

        pwdInfoDao = new PwdInfoDao(pwdInfoDaoConfig, this);

        registerDao(PwdInfo.class, pwdInfoDao);
    }
    
    public void clear() {
        pwdInfoDaoConfig.clearIdentityScope();
    }

    public PwdInfoDao getPwdInfoDao() {
        return pwdInfoDao;
    }

}
