package com.lyh.cn.passwordbook.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lyh.cn.passwordbook.model.PwdInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PWD_INFO".
*/
public class PwdInfoDao extends AbstractDao<PwdInfo, Long> {

    public static final String TABLENAME = "PWD_INFO";

    /**
     * Properties of entity PwdInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WebSiteName = new Property(1, String.class, "webSiteName", false, "SITENAME");
        public final static Property WebSiteUrl = new Property(2, String.class, "webSiteUrl", false, "SITEURL");
        public final static Property Email = new Property(3, String.class, "email", false, "EMAIL");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property Password = new Property(5, String.class, "password", false, "PASSWORD");
        public final static Property Remarks = new Property(6, String.class, "remarks", false, "REMARKS");
    }


    public PwdInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PwdInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PWD_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SITENAME\" TEXT," + // 1: webSiteName
                "\"SITEURL\" TEXT," + // 2: webSiteUrl
                "\"EMAIL\" TEXT," + // 3: email
                "\"PHONE\" TEXT," + // 4: phone
                "\"PASSWORD\" TEXT," + // 5: password
                "\"REMARKS\" TEXT);"); // 6: remarks
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PWD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PwdInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String webSiteName = entity.getWebSiteName();
        if (webSiteName != null) {
            stmt.bindString(2, webSiteName);
        }
 
        String webSiteUrl = entity.getWebSiteUrl();
        if (webSiteUrl != null) {
            stmt.bindString(3, webSiteUrl);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(4, email);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(6, password);
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(7, remarks);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PwdInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String webSiteName = entity.getWebSiteName();
        if (webSiteName != null) {
            stmt.bindString(2, webSiteName);
        }
 
        String webSiteUrl = entity.getWebSiteUrl();
        if (webSiteUrl != null) {
            stmt.bindString(3, webSiteUrl);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(4, email);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(6, password);
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(7, remarks);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PwdInfo readEntity(Cursor cursor, int offset) {
        PwdInfo entity = new PwdInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // webSiteName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // webSiteUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // email
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // password
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // remarks
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PwdInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWebSiteName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWebSiteUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEmail(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPassword(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemarks(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PwdInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PwdInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PwdInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
